# Generated by Django 5.2.15 on 2026-07-09 02:20

import comptes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('MECANICIEN', 'Mécanicien'), ('GESTIONNAIRE', 'Gestionnaire')], default='CLIENT', help_text="Le rôle détermine les fonctionnalités accessibles. L'inscription publique ne crée que des comptes CLIENT ; les rôles MECANICIEN et GESTIONNAIRE sont attribués via l'administration.", max_length=15)),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[comptes.models.valider_telephone_quebec])),
                ('adresse', models.CharField(blank=True, max_length=150)),
                ('ville', models.CharField(blank=True, max_length=80)),
                ('province', models.CharField(blank=True, default='Québec', max_length=50)),
                ('code_postal', models.CharField(blank=True, max_length=10, validators=[comptes.models.valider_code_postal_canadien])),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True, help_text="Pour un mécanicien : indique s'il peut actuellement recevoir de nouvelles réparations à affecter. Sans effet pour les autres rôles.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
    ]
