# Generated by Django 5.2.15 on 2026-07-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_utilisateur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('MECANICIEN', 'Mécanicien'), ('GESTIONNAIRE', 'Gestionnaire'), ('ADMINISTRATEUR', 'Administrateur')], default='CLIENT', max_length=20),
        ),
    ]
