# Generated by Django 6.0.6 on 2026-07-15 23:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reparations', '0003_alter_demandereparation_id_alter_typereparation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro de facture')),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('montant_main_oeuvre', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Montant main-d'œuvre")),
                ('montant_pieces', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant pièces')),
                ('tps', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('tvq', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('montant_total', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('statut', models.CharField(choices=[('emise', 'Émise'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='emise', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='reparations.demandereparation', verbose_name='Demande de réparation')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission', '-id'],
            },
        ),
    ]
