# Generated by Django 5.2.15 on 2026-07-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparations', '0002_typereparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandereparation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='typereparation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
