# Generated by Django 5.2.15 on 2026-07-09 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeReparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Résumé court du problème (ex: Bruit anormal au freinage)', max_length=120)),
                ('description_probleme', models.TextField(help_text='Description détaillée du problème rencontré par le client.')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_TRAITEMENT', 'En traitement'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_reparation', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_reparation', to='vehicules.vehicule', verbose_name='Véhicule concerné')),
            ],
            options={
                'verbose_name': 'Demande de réparation',
                'verbose_name_plural': 'Demandes de réparation',
                'ordering': ['-date_creation'],
            },
        ),
    ]
