# Generated by Django 5.2.15 on 2026-07-09 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes_reparation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, help_text='Note interne du gestionnaire (facultatif).')),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('affecte_par', models.ForeignKey(help_text="Le gestionnaire (ou administrateur) ayant réalisé l'affectation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_realisees', to=settings.AUTH_USER_MODEL, verbose_name='Affecté par')),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affectation', to='demandes_reparation.demandereparation', verbose_name='Demande de réparation')),
                ('mecanicien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to=settings.AUTH_USER_MODEL, verbose_name='Mécanicien assigné')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['-date_affectation'],
            },
        ),
    ]
