# Generated by Django 6.0.6 on 2026-07-05 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('vehicule', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_intervention', models.DateField()),
                ('duree_heures', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pieces_utilisees', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée')], default='en_cours', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('mecanicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_intervention'],
            },
        ),
    ]
