# Generated by Django 5.2.15 on 2026-07-11 11:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reparations', '0003_alter_demandereparation_id_alter_typereparation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_techniques', models.TextField(help_text='Observations techniques du mécanicien (cause du problème, état constaté).')),
                ('travaux_a_effectuer', models.TextField(help_text='Description des réparations proposées au client.')),
                ('cout_estime', models.DecimalField(decimal_places=2, help_text='Montant estimé du devis, en dollars canadiens.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'En attente de validation du client'), ('ACCEPTE', 'Accepté par le client'), ('REFUSE', 'Refusé par le client')], default='EN_ATTENTE_VALIDATION', max_length=25)),
                ('commentaire_client', models.TextField(blank=True, help_text='Motif du refus, fourni par le client (facultatif).')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_reponse_client', models.DateTimeField(blank=True, null=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='reparations.demandereparation', verbose_name='Demande de réparation')),
                ('mecanicien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostics', to=settings.AUTH_USER_MODEL, verbose_name='Mécanicien')),
            ],
            options={
                'verbose_name': 'Diagnostic',
                'verbose_name_plural': 'Diagnostics',
                'ordering': ['-date_creation'],
            },
        ),
    ]
