# Generated by Django 6.0.6 on 2026-07-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
        ('reparations', '0003_alter_demandereparation_id_alter_typereparation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='types_reparation',
            field=models.ManyToManyField(blank=True, related_name='diagnostics', to='reparations.typereparation', verbose_name='Types de réparation'),
        ),
    ]
